# constants.py
REGULAR_LANE_CAPACITY = 5
SELF_SERVICE_LANE_CAPACITY = 15
MAX_ITEMS_IN_BASKET = 30
MAX_INITIAL_CUSTOMERS = 10
MAX_CUSTOMERS_IN_STORE = 40
CHECKOUT_TIME_REGULAR = 4  # seconds per item
CHECKOUT_TIME_SELF_SERVICE = 6  # seconds per item
SIMULATION_DURATION = 36000
